{{- if and .Values.crunchy.enabled .Values.crunchy.pgBackRest.s3.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-s3-secret
type: Opaque
stringData:
  s3.conf: |-
        {{ include "crunchy.s3" . | nindent 8}}
{{- end }}

{{- if and .Values.crunchy.enabled .Values.crunchy.pgUser.customPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}-pguser-{{ .Values.global.config.dbName }}
  labels:
    postgres-operator.crunchydata.com/cluster: {{ template "crunchy-postgres.fullname" . }}
    postgres-operator.crunchydata.com/pguser: {{ .Values.global.config.dbName }}
    {{ include "crunchy-postgres.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.crunchy.pgUser.customPassword }}
{{- end }}
