{{/*
Secret for S3 backup credentials
This secret is created when S3 backups are enabled and stores the S3 access credentials.
The actual credentials (accessKeyId and accessKeySecret) are passed via --set during deployment.
*/}}
{{- if and .Values.pgBackRest.s3.enabled .Values.pgBackRest.s3.createS3Secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgBackRest.s3.secretName }}
type: Opaque
data:
  {{- $args := dict "s3" .Values.pgBackRest.s3 "index" 1 }}
  s3.conf: |-
        {{ include "crunchy.s3" $args | b64enc }}
{{- end }}