name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  remove-db:
    name: Remove Crunchy
    runs-on: ubuntu-24.04
    steps:
      - name: Cleanup Database
        id: cleanup-db
        uses: bcgov/action-oc-runner@f900830adadd4d9eef3ca6ff80103e839ba8b7c0 # v1.3.0
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          commands: |
            helm uninstall pg-b80f1343 || true
            helm uninstall pg-action || true
