name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup-db: # TODO move it off to another action later.
    name: Remove DB User from Crunchy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup Database
        id: cleanup-db
        uses: ./
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }}
