name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  deploy-db:
    name: Deploy Database
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Deploy Database
        id: deploy_db
        uses: ./
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          ref: ${{ github.ref }}
          values_file: values.yml
          s3_access_key: ${{ secrets.s3_access_key }}
          s3_secret_key: ${{ secrets.s3_secret_key }}
          s3_bucket: ${{ secrets.s3_bucket }}
          s3_endpoint: ${{ secrets.s3_endpoint }}
          force_cleanup: true

      - run: |
          echo "Outputs: ${{ toJSON(steps.deploy_db.outputs) }}"
      
      - if: contains(steps.deploy_db.outputs.* , '')
        run: |
          echo "Error! At least one output is empty. Verify outputs." && exit 1

  results:
    name: Results
    needs: [deploy-db]
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
