name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  deploy-db:
    name: Deploy Database
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Database
        id: deploy_db
        uses: ./
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_server: ${{ secrets.oc_server }}
          oc_token: ${{ secrets.oc_token }}
          postgres_version: 16
          postgis_version: 3.4

  results:
    name: Results
    needs: [deploy-db]
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
